# Generated by Django 3.0.7 on 2020-07-08 11:43

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_contact_catch_phrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, height_field=30, null=True, upload_to=chat.models.upload_path, width_field=30),
        ),
    ]
