# Generated by Django 3.0.7 on 2020-07-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20200708_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='warning',
            field=models.BooleanField(default=False),
        ),
    ]
