# Generated by Django 3.0.7 on 2020-07-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_animation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='bgColor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='animation',
            name='startConfetti',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
