# Generated by Django 3.0.7 on 2020-08-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20200726_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='online',
            field=models.BooleanField(default=True),
        ),
    ]
